### ISSUE TITLE
When I set the endpoint as 'bucket.oss-cn-hangzhou-internal.aliyuncs.com', the docker registry fail to start.

### ISSUE THREAD

**Issue by firelyu** [denverdino/aliyungo#33]
I use the `OSS` as the docker registry backend. The registry container run on the ECS, I want to connect to `OSS` with internal endpoint. I get the internal endpoint url from [ali guide][1].
```
storage:
    oss:
        accesskeyid: xxxxxxx
        accesskeysecret: yyyyyyyy
        region: oss-cn-hangzhou
        endpoint: bucket1.oss-cn-hangzhou-internal.aliyuncs.com
        internal: true
        bucket: bucket1
```
When I start the registry, it error out.
```go
2016/01/23 06:42:41 GET https://bucket1.oss-cn-hangzhou-internal.aliyuncs.com/?delimiter=&marker=&max-keys=1&prefix=test ...
panic: Get https://bucket1.oss-cn-hangzhou-internal.aliyuncs.com/?delimiter=&marker=&max-keys=1&prefix=test: x509: certificate is valid for *.oss-internal.aliyuncs.com, not registry1.oss-cn-hangzhou-internal.aliyuncs.com
```
[1]:https://help.aliyun.com/document_detail/oss/user_guide/oss_concept/endpoint.html?spm=5176.docoss/user_guide/oss_concept/concepts.2.4.0Ie7lg

**Comment by denverdino** [comment]
I am not quite sure for the reason
you can disable the SSL certification, by setting the following section to oss configuration
"secure: false"

**Comment by tg123** [comment]
`openssl s_client -connect  bucket1.oss-cn-hangzhou-internal.aliyuncs.com:443`
info may help

**Comment by firelyu** [comment]
@denverdino  When I set the `secure:false`, I can start the registry with `http`. BTW, in the [OSS guide][1], by default, the `secure` is `false`. But, in the registry 2.2.+, the default is `true`.

@tg123 I will try to download the SSL certification.

Thank all for the help.

[1]:https://docs.docker.com/registry/storage-drivers/oss/

**Comment by firelyu** [comment]
@tg123 I download the pem.
```
# openssl s_client  -connect bucket1.oss-cn-hangzhou-internal.aliyuncs.com:443  -showcerts </dev/null 2>/dev/null | openssl x509 -outform PEM >oss.pem
```
But I can't use it.
```
# curl --cacert registry/certs/oss.pem https://bucket1.oss-cn-hangzhou-internal.aliyuncs.com
curl: (51) SSL: no alternative certificate subject name matches target host name 'bucket1.oss-cn-hangzhou-internal.aliyuncs.com'
```
It seems the certification is for `*.oss-internal.aliyuncs.com`, not for `*.oss-cn-hangzhou-internal.aliyuncs.com`

**Comment by tg123** [comment]
hi @denverdino 
maybe aliyun use wrong cert

cloud you please forward this message to aliyun ops team?

**Comment by denverdino** [comment]
Sure, I will do

**Comment by firelyu** [comment]
Waiting for the update.

**Comment by denverdino** [comment]
Sorry for late response, I was on training recently.

It is current design to use the cert for *.oss-internal.aliyuncs.com for the Internal access in Hangzhou region.

Is that possible for you to set the endpoint url in the registry config

endpoint: bucket1.oss-cn-hangzhou-internal.aliyuncs.com

Then the registry will use the configured URL for OSS access. 

Thanks again

**Comment by firelyu** [comment]
When I set the endpoint as the following and enable the secure. 
```yaml
endpoint: bucket1.oss-cn-hangzhou-internal.aliyuncs.com
secure: true
region: oss-cn-hangzhou
bucket: bucket1
```
The registry panic.
```
panic: Get https://bucket1.oss-cn-hangzhou-internal.aliyuncs.com/?delimiter=&marker=&max-keys=1&prefix=test: x509: certificate is valid for *.oss-internal.aliyuncs.com, not registry1.oss-cn-hangzhou-internal.aliyuncs.com
```

If I disable the `secure`, the endpoint works.
```yaml
endpoint: bucket1.oss-cn-hangzhou-internal.aliyuncs.com
secure: false
region: oss-cn-hangzhou
bucket: bucket1
```
```
registry_1      | 2016/01/30 02:03:36 GET http://bucket1.oss-cn-hangzhou-internal.aliyuncs.com/?delimiter=&marker=&max-keys=1&prefix=test ...
```

**Comment by firelyu** [comment]
The cert only support `*.oss-internal.aliyuncs.com`, not `*.oss-cn-hangzhou-internal.aliyuncs.com`.
```yaml
endpoint: bucket1.oss-internal.aliyuncs.com
secure: true
region: oss-cn-hangzhou
bucket: bucket1
```
```
registry_1      | 2016/01/30 02:08:28 GET https://bucket1.oss-internal.aliyuncs.com/?delimiter=&marker=&max-keys=1&prefix=test ...
```
I can use `oss-internal.aliyuncs.com` with `https` for hangzhou. But how can I use the oss with secure for `beijing`, `shanghai`?
From the [guide][1], the `oss-internal.aliyuncs.com` is only for hangzhou.
```
原地址oss.aliyuncs.com 默认指向杭州节点外网地址
原内网地址oss-internal.aliyuncs.com 默认指向杭州节点内网地址
```

[1]:https://help.aliyun.com/document_detail/oss/user_guide/endpoint_region.html?spm=5176.docoss/user_guide/oss_concept/endpoint.2.1.8RDAQe
